[versions]
# Plugins
androidGradlePlugin = "9.0.0"
kotlinGradlePlugin = "2.3.0"
ksp = "2.3.2"

detektGradlePlugin = "1.23.8"
googleSecretsPlugin = "2.0.1"
automatticMeasureBuilds = "3.2.2"
# Core
androidxComposeBom = "2026.01.00"
activityCompose = "1.12.2"

coreKtx = "1.17.0"
lifecycle = "2.10.0"

retrofit = "3.0.0"
okHttp = "5.3.2"
coroutine = "1.10.2"
gson = "2.13.2"
coil = "3.3.0"

koinBom = "4.1.1"
koinAnnotations = "2.3.1"

nav3Core = "1.0.0"
lifecycleViewmodelNav3 = "2.10.0"
kotlinxSerializationCore = "1.9.0"
material3AdaptiveNav3 = "1.0.0-SNAPSHOT"

# Testing
junit = "4.13.2"
junitExt = "1.3.0"
espressoCore = "3.7.0"
turbine = "1.2.1"

[libraries]
# Define the libraries
# Lifecycle
lifecycle_runtime_ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle_viewmodel_compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle_runtime_compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle_viewmodel_testing = { module = "androidx.lifecycle:lifecycle-viewmodel-testing", version.ref = "lifecycle" }

# Compose libraries
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
compose_ui = { group = "androidx.compose.ui", name = "ui" }
compose_tooling_preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose_tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose_ui_test_manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose_material3 = { group = "androidx.compose.material3", name = "material3" }
compose_icons = { group = "androidx.compose.material", name = "material-icons-extended" }
compose_ui_test_junit = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# Activity
activity_compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
# Retrofit
retrofit_core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit_gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okHttp" }
# Gson
gson_core = { module = "com.google.code.gson:gson", version.ref = "gson" }
# Coil
coil_core = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil_compose = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil" }
coil_network_okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coil_testing = { module = "io.coil-kt.coil3:coil-test", version.ref = "coil" }
# Coroutines
coroutine_core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
coroutine_android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
coroutine_test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutine" }
# Koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }
koin-androidx-startup = { group = "io.insert-koin", name = "koin-androidx-startup" }
koin-test = { group = "io.insert-koin", name = "koin-test" }
koin-test-junit4 = { group = "io.insert-koin", name = "koin-test-junit4" }

koin-annotations-core = { group = "io.insert-koin", name = "koin-annotations" , version.ref= "koinAnnotations" }
koin-annotations-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref= "koinAnnotations" }

# Core Navigation 3 libraries
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }

# Optional add-on libraries
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }

# Note: The Material3 adaptive layouts library for Navigation 3 is currently
# only available in snapshot builds. Follow the instructions at androidx.dev to
# add the snapshot builds repository to your project.
androidx-material3-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3AdaptiveNav3" }


# Android core
core_ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
# Test
junit = { module = "junit:junit", version.ref = "junit" }
# AndroidTest
test_ext = { module = "androidx.test.ext:junit", version.ref = "junitExt" }
test_espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
##Plugins
dep-google-secrets-gradle-plugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "googleSecretsPlugin" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[bundles]
# Define bundles/groups of libraries
compose = ["compose_ui", "compose_material3", "compose_tooling_preview", "compose_icons"]
compose_debug = ["compose_tooling", "compose_ui_test_manifest"]
coroutine = ["coroutine_core", "coroutine_android"]
retrofit = ["retrofit_core", "retrofit_gson"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektGradlePlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "googleSecretsPlugin" }
automattic-measure-builds = { id = "com.automattic.android.measure-builds", version.ref = "automatticMeasureBuilds" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinGradlePlugin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinGradlePlugin"}
